# -*- coding: utf-8 -*-
"""Assignment class room1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxcQI8Sw1C5zggo4Fm4NAtwkYrWkVLZ_
"""

n=int(input("enter the number"))
i=1
for a in range(1,n+1):
  i=i*a
print(i)

x=int(input("enter the number"))
j=x
while x>=0:
  print(x)
  x-=1

l1=['bhanu','good','boy']
for a in l1:
  print(a.upper())

n=int(input('enter a number'))
r=0
while n>0:
    digit = n%10
    r = (r * 10) + digit
    n = n//10
    print(r)

l = ['Akhkmlkl','sharma','bhanu','audrrrrrrdq']
count = 0
for i in l:
    if (len(i)>count):
        count = len(i)
        str = i
print(count)
print(str)

s = "bhanu"
rev = ''
for i in s:
    rev = i + rev
print(rev)

n=2

while(n<=50):
    if(n%2!=0):
        print(n,end = ', ')
    n+=1

n = int(input("Enter a Value"))
sum = 0
while(n!=0):
    digit = n%10
    sum = sum + digit
    n = n//10
print(sum)

d = {'Name':'bhanu','Class':10,'Course':' big Data'}
for i,j in d.items():
    print(f" {i}:{j} ")