# -*- coding: utf-8 -*-
"""Assignment hoilday2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANqRcM_1PAPyr8RgHf539KoB9TNTMg2b

Perform division between two numbers and then use the floor division (//) operator to get the
integer result.
"""

a = 9
b = 8

print(a//b)

"""Compare two floating-point numbers using == to check if they are approximately equal. Consider
using round() for comparison.
"""

a = 1.3
b = 12.3
print(a==b)

"""Given two boolean variables, use and and or to determine all possible outcomes (e.g., True and
False).
"""

a = True
b = False

print(a and b)
print(a or b)

"""Use the bitwise OR (|) operator to combine two integer values."""

a = 5
b = 10
print(a|b)

"""Concatenate two strings without using the + operator (hint: use join())."""

a = "bhanu"
b = "sharma"
print(a+b)

"""Format a string using f-strings to include variables within the string."""

name = 'bhanu'
weight = 70
print(f"My name is {name}  my body weight is {weight}.")

"""Slice a string to extract the first three characters."""

a = "bhanu"
print(a[:3])

"""Convert a string like &quot;123&quot; into an integer using int()."""

a = "123"
b = int(a)
print(type(b),b)

"""Access the last element of a list using negative indexing."""

l1 = [1,2,3,4]
print(l1[-1])

"""Slice a list to get every second element from the start to the end."""

l1 = [1,2,3,4,5,6,7,8]
print(l1[0:8:2])

l1 = [1,2,9,6,7,8]
l2=[1,23,4]
print(l2 + l1)

1 in l1

l1

l1
l1.sort()
print(l1)

l1.extend(l1)
print(l1)
l1.index(2)

l2 = [1, 2, 3, 4, 5, 6,4,56]
sl = l2[1:4]
print(sl)

print(len(l2))

l1 = [1, 2, 3]
t = tuple(l1)
print(type(t),t)

print(t[2])

print(t*3)

a = "bhanu"
b = "sharma"

print(b>a)

a=1
b=2
c=3
result = (a and b) or (a and c) or (b and c)
print(result)