# -*- coding: utf-8 -*-
"""Session9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wLXYn9WJgSsS5v-6SUlF5UzYJJbWBjx
"""

#loop
#(2) while

 #while conditon
     #code_to_run

i=0
while i<5:
  print(i)
  i+=1

j=3
while j>0:
    print(j)
    j-=1

j=9
while j>0:     #odd number
  print(i)
  j-=2

#if else (condition statements)
#if elif else
#if ---------------condion(1)
#elif-----------------condition(mul.)
#else------------(1)



x=int(intput())
if x>5:
  print("x is greater than 5")
elif x<5:
    print("x is less than 5")
elif :
    print("x is equal than 5")

x=int(input())
i=1
while i<11:
  print(f'{x}*{i}={x*i}')
  i+=1

j=2
while j<10:     #even number
  print(i)
  j+=1

